### ISSUE TITLE
vs other related libs....

### ISSUE THREAD

**Issue by sirvon** [SalomonBrys/Android-FragmentArgumentProcessor#1]
thanks for this lib!

Can you glance at this lib:

https://github.com/sockeqwe/fragmentargs

and tell me why this one is diff/better/etc.

thanks!

**Comment by SalomonBrys** [comment]
Well, Android-FAP is older than FragmentArgs but FragmentArgs has definitely more features and since I am not planning on putting Android-FAP up to speed, I'd definitely recommend using FragmentArgs ;)
